package org.dselent.course_load_scheduler.client.receive.jsonkeys;

// TODO
// Design this correctly
public enum KeyPrefix
{
	CALENDAR_INFO,
	COURSE_INFO,
	INSTRUCTOR_INFO,
	INSTRUCTOR_INFO_HISTORY,
	LAB_INFO,
	NOTIFICATION,
	SCHEDULE_LINKS,
	SECTION_INFO,
	SECTION_POPULATION,
	USER_INFO,
	USER_INFO_HISTORY,
	USER_ROLE,
	USERS_ROLES_LINK,
	USER_STATE,
	WISHLIST_LINKS;
}
