package org.dselent.course_load_scheduler.client.view;

import org.dselent.course_load_scheduler.client.presenter.AccountsPresenter;

import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.Grid;
import com.google.gwt.user.client.ui.HorizontalPanel;
import com.google.gwt.user.client.ui.IntegerBox;
import com.google.gwt.user.client.ui.Label;
import com.google.gwt.user.client.ui.ListBox;
import com.google.gwt.user.client.ui.MenuBar;
import com.google.gwt.user.client.ui.MenuItem;
import com.google.gwt.user.client.ui.RadioButton;
import com.google.gwt.user.client.ui.TextBox;

public interface AccountsView extends BaseView<AccountsPresenter>
{
	TextBox getEnterUserName();
	void setEnterUserName(TextBox enterUserName);
	TextBox getEnterFirstName();
	void setEnterFirstName(TextBox enterFirstName);
	Button getButtonEdit();
	void setButtonEdit(Button buttonEdit);
	Button getButtonApply();
	void setButtonApply(Button buttonApply);
	Button getButtonCancel();
	void setButtonCancel(Button buttonCancel);
	Button getButtonRemove();
	void setButtonRemove(Button buttonRemove);
	Button getButtonCreate();
	void setButtonCreate(Button buttonCreate);
	RadioButton getRadioSortDepartment();
	void setRadioSortDepartment(RadioButton radioSortDepartment);
	RadioButton getRadioSortName();
	void setRadioSortName(RadioButton radioSortName);
	HorizontalPanel getRadioPanel();
	void setRadioPanel(HorizontalPanel radioPanel);
	Grid getFullGrid();
	void setFullGrid(Grid fullGrid);
	ListBox getListAccounts();
	void setListAccounts(ListBox listAccounts);
	Grid getGridEditing();
	void setGridEditing(Grid gridEditing);
	TextBox getEnterLastName();
	void setEnterLastName(TextBox enterLastName);
	TextBox getEnterDepartment();
	void setEnterDepartment(TextBox enterDepartment);
	IntegerBox getEnterRank();
	void setEnterRank(IntegerBox enterRank);
	IntegerBox getEnterCourseLoad();
	void setEnterCourseLoad(IntegerBox enterCourseLoad);
	TextBox getEnterOffice();
	void setEnterOffice(TextBox enterOffice);
	MenuBar getMenuPrivelages();
	void setMenuPrivelages(MenuBar menuPrivelages);
	MenuItem getDropdownAdmin();
	void setDropdownAdmin(MenuItem dropdownAdmin);
	MenuItem getDropdownNonAdmin();
	void setDropdownNonAdmin(MenuItem dropdownNonAdmin);
	TextBox getEnterEmail();
	void setEnterEmail(TextBox enterEmail);
	Button getButtonViewAccount();
	void setButtonViewAccount(Button buttonViewAccount);
	Button getButtonSort();
	void setButtonSort(Button buttonSort);
	Label getLabelUserName();
	Label getLabelFirstName();
	Label getLabelSort();
	Label getLabelLastName();
	Label getLabelDepartment();
	Label getLabelRank();
	Label getLabelCourseLoad();
	Label getLabelOffice();
	Label getLabelPrivelages();
	Label getLabelEmail();
}
